qa/urls.py
from django.urls import path

app_name="qa"

urlpatterns = [
    # path("dashboard", DashboardView.as_view(), name="dashboard")
]

risk_mgmt_compilance_mapping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user.urls", namespace="user")),
    path('', include("dashboard.urls", namespace="dashboard")),
    path('', include("qa.urls", namespace="qa")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_title = "RMT site admin (DEV)"
admin.site.site_header = "RMT administration"
admin.site.index_title = "RMT administration"

user/urls.py
from django.urls import path
from user.views import (
    LoginView,
    RegisterView,
    LogoutView,
)

app_name="user"

urlpatterns = [
    path("", LoginView.as_view(), name="user_login"),
    path("register/", RegisterView.as_view(), name="user_register"),
    path("logout/", LogoutView.as_view(), name="user_logout"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from utils.models import AbstractTimeStampModel
from .manager import CustomUserManager


# Create your models here.

class User(AbstractUser, AbstractTimeStampModel):
    username = None
    first_name = models.CharField(verbose_name="first name",
        max_length=100,
        help_text="Required. 100 characters or fewer.",
    )
    last_name = models.CharField(verbose_name="last name", max_length=100,
        help_text="Required. 100 characters or fewer.",
    )
    email = models.EmailField( verbose_name="email address", unique=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = CustomUserManager()

    class Meta:
        db_table = "user"

user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .models import User


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "password1", "password2"]


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

user/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import LoginForm, CustomUserCreationForm
from django.contrib.auth import authenticate, login, logout


class LoginView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('dashboard:dash')
        form = LoginForm()
        return render(request, 'user/login.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('dashboard:dash')
            else:
                error_message = "Invalid email or password."
                return render(request, 'user/login.html', {'form': form, 'error_message': error_message})
        else:
            return render(request, 'user/login.html', {'form': form})


class RegisterView(View):
    def get(self, request, *args, **kwargs):
        form = CustomUserCreationForm()
        context = {"form": form}
        return render(request, "user/register.html", context)
    
    def post(self, request, *args, **kwargs):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.is_active = True
            user.save()
            return redirect("user:user_login")
        else:
            return render(request, "user/register.html", {"form": form})
        

class LogoutView(View):
    def post(self, request, *args, **kwargs):
        if request.method=="POST":
            logout(request)
            return redirect("user:user_login")

user/templates/user/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block static %}
<style>
    /* Center the form vertically */
    .center-form {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }
    /* Set the width of the form container */
    .form-container {
        max-width: 400px; /* Adjust the width as needed */
        width: 100%;
    }
    .center-form{
      font-weight:900;

    }
  </style>

{% endblock static %}

{% block content %}

<div class="container-fluid">
    <div class="container center-form">
        <div class="row">
          <div class="col">
            <!-- Logo Section -->
            
      
            <!-- Login Form -->
            <div class="card form-container shadow-sm login_form shadow-sm p-3 rounded-4">
              <div class="card-body">
                <h4 class="card-title text-center">Login</h4>
                {% if error_message %}
                    <div class="p-4">
                        <div class="container">
                            <div class="row">
                                <div class="col">
                                    <div class="alert alert-danger">
                                        {{ error_message }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                  <div class="d-grid gap-2 mt-4">
                    <button class="btn btn-primary" type="submit">Login</button>
                  </div>
                </form>
                <br>
                <span>Don't have an account <a href=" {% url "user:user_register" %} " >Create One ?</a> </span>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>


{% endblock content %}

user/templates/user/register.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block static %}
<style>
    /* Center the form vertically */
    .center-form {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }
    /* Set the width of the form container */
    .form-container {
        max-width: 500px; /* Adjust the width as needed */
        width: 100%;
    }
    .center-form{
      font-weight:900;

    }
  </style>

{% endblock static %}

{% block content %}

<div class="container-fluid">
    <div class="container center-form">
        <div class="row">
          <div class="col">
            <!-- Logo Section -->
            
      
            <!-- Login Form -->
            <div class="card form-container shadow-sm login_form shadow-sm p-2 rounded-4">
              <div class="card-body">
                <h4 class="card-title text-center">Register</h4>
                {% if messages %}
                    <div class="p-4">
                        <div class="container">
                            <div class="row">
                                <div class="col">
                                    {% for message in messages %}
                                    <div class="alert alert-danger">
                                        {{ message }}
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {% comment %} {{ form|crispy }} {% endcomment %}

                    <div class="mb-3">
                        <div class="row">
                            <div class="col-md-6">
                                {{ form.first_name|as_crispy_field }}
                            </div>
                            <div class="col-md-6">
                                {{ form.last_name|as_crispy_field }}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-md-6">
                                {{ form.password1|as_crispy_field }}
                            </div>
                            <div class="col-md-6">
                                {{ form.password2|as_crispy_field }}
                            </div>
                        </div>
                    </div>
                    <div class="d-grid gap-2 mt-4">
                        <button class="btn btn-primary" type="submit">Register</button>
                    </div>
                </form>
                <br>
                <span>Already have an account <a href=" {% url "user:user_login" %} " >Login</a> </span>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>


{% endblock content %}