dashboard/urls.py
from django.urls import path
from dashboard.views import (
    DashView,
    DashboardView,
    RiskAssessmentAttemptView,
    CommonThreatView,
    AssetsView,
    AssetsUploadView,
    ExportAssetsDataView,
    TrainingsView,
    ComplianceView,
    CompilanceQAAttemptView,
    AboutView,
    RiskRegisterView,
    RiskRegisterCreateView,
    RiskRegisterUpdateView,
    RiskRegisterDeleteView,
)

app_name="dashboard"

urlpatterns = [
    path("dashboard", DashView.as_view(), name="dash"),
    path("risk-assessment", DashboardView.as_view(), name="dashboard"),
    path("rist-assessment-attempt", RiskAssessmentAttemptView.as_view(), name="risk_assessment_attempt"),
    path("common-threat", CommonThreatView.as_view(), name="common_threat"),
    path("assets", AssetsView.as_view(), name="assets"),
    path("assets-upload", AssetsUploadView.as_view(), name="assets_upload"),
    path("assets-export", ExportAssetsDataView.as_view(), name="assets_export"),
    path("trainings", TrainingsView.as_view(), name="trainings"),
    path("compilance", ComplianceView.as_view(), name="compilance"),
    path("compilance-qa-attempt", CompilanceQAAttemptView.as_view(), name="compilance_qa_attempt"),
    path("about-us", AboutView.as_view(), name="about"),
    path("risk-register", RiskRegisterView.as_view(), name="risk_register"),
    path("risk-register-create", RiskRegisterCreateView.as_view(), name="risk_register_create"),
    path("risk-register/<int:pk>/update", RiskRegisterUpdateView.as_view(), name="risk_register_update"),
    path("risk-register/<int:pk>/delete", RiskRegisterDeleteView.as_view(), name="risk_register_delete"),
]

qa/urls.py
from django.urls import path

app_name="qa"

urlpatterns = [
    # path("dashboard", DashboardView.as_view(), name="dashboard")
]

risk_mgmt_compilance_mapping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user.urls", namespace="user")),
    path('', include("dashboard.urls", namespace="dashboard")),
    path('', include("qa.urls", namespace="qa")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_title = "RMT site admin (DEV)"
admin.site.site_header = "RMT administration"
admin.site.index_title = "RMT administration"

dashboard/models.py
from django.db import models
from utils.models import AbstractTimeStampModel
from user.models import User

class About(AbstractTimeStampModel):
    title = models.CharField(max_length=255)
    description = models.TextField()

    class Meta:
        verbose_name = "About"
        verbose_name_plural = "About"
        db_table = "about"

    def __str__(self):
        return self.title
    

class Assets(AbstractTimeStampModel):
    user = models.ForeignKey(User, verbose_name="User", on_delete=models.CASCADE)
    host_name = models.CharField(max_length=255, verbose_name="Host Name")
    ip_address = models.CharField(max_length=255, verbose_name="IP Address", null=True, blank=True)
    os = models.CharField(max_length=255, verbose_name="OS", null=True, blank=True)
    software = models.CharField(max_length=255, verbose_name="Software", null=True, blank=True)
    other = models.JSONField(default=dict, verbose_name="Other")
    
    class Meta:
        verbose_name = "Assets"
        verbose_name_plural = "Assets"
        db_table = "assets"

    def __str__(self):
        return self.host_name
    


class RiskScale(AbstractTimeStampModel):
    number = models.IntegerField(default=0, verbose_name="Number")
    color_code = models.CharField(max_length=20, verbose_name="Hex Color Code")
    other = models.JSONField(default=dict, verbose_name="Other", null=True, blank=True)

    class Meta:
        verbose_name = "RiskScale"
        verbose_name_plural = "RiskScale"
        db_table = "risk_scale"

    def __str__(self):
        return f"Number: {self.number} Color Code {self.color_code}"
    

class RiskRegister(AbstractTimeStampModel):
    LEVEL_CHOICES = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]
    user = models.ForeignKey(User, verbose_name="User", on_delete=models.CASCADE)
    risk_description = models.TextField(verbose_name="Risk Description", help_text="Give a brief summary of the risk.")
    impact_description = models.TextField(verbose_name="Impact Description", help_text="What will happen if the risk is not mitigated or eliminated?.")
    impact_level = models.IntegerField(choices=LEVEL_CHOICES, verbose_name="Impact Level", help_text="Rate 1 (LOW) to 5 (HIGH).")
    probability_level = models.IntegerField(choices=LEVEL_CHOICES, verbose_name="Probability Level", help_text="Rate 1 (LOW) to 5 (HIGH).")
    migrations_notes = models.TextField(verbose_name="Migration Notes", help_text="What can be done to lower or eliminate the impact or probability?")
    owner = models.TextField(verbose_name="Owner", help_text="Who's responsible?")
    other = models.JSONField(default=dict, verbose_name="Other", null=True, blank=True)

    class Meta:
        verbose_name = "RiskRegister"
        verbose_name_plural = "RiskRegister"
        db_table = "risk_register"

    def __str__(self):
        return self.risk_description

dashboard/forms.py
from django import forms
from qa.models import UserAttempt
from .models import RiskRegister

class RiskAssessmentForm(forms.ModelForm):
    class Meta:
        model = UserAttempt
        fields = ["question", "selected_answer"]


class RiskRegisterForm(forms.ModelForm):
    class Meta:
        model = RiskRegister
        fields = ["risk_description", "impact_description", "impact_level", "probability_level", "migrations_notes", "owner"]
        widgets = {
            'risk_description': forms.Textarea(attrs={'rows': 1}),
            'impact_description': forms.Textarea(attrs={'rows': 1}),
            'migrations_notes': forms.Textarea(attrs={'rows': 1}),
            'owner': forms.Textarea(attrs={'rows': 1})
        }
    
    def __init__(self, *args, **kwargs):
        super(RiskRegisterForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['risk_description'].initial = self.instance.risk_description
            self.fields['impact_description'].initial = self.instance.impact_description
            self.fields['migrations_notes'].initial = self.instance.migrations_notes
            self.fields['owner'].initial = self.instance.owner

dashboard/views.py
import json

from decimal import Decimal
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import View
from qa.models import (
    Question,
    Answer,
    UserAttempt
)
from .models import About, Assets, RiskScale, RiskRegister
from .utils import validate_and_import_csv, export_assets_data
from .OpenCVE.datas import OPENCVEDB_DATA

class DashView(View):
    def get(self, request, *args, **kwargs):
        context = {"title":"dash"}
        return render(request, "dashboard/dash.html", context)

class DashboardView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_attempt = UserAttempt.objects.filter(
            user = request.user,
            all_question_attempted = True,
            question__question_type__type="Type A"
        )
        context = {"title":"dashboard"}
        if user_attempt.exists():
            earned_points = Decimal('0.0')
            for attempted in user_attempt:
                earned_points += attempted.points_earned if attempted.points_earned else Decimal('0.0')
            context["earned_points"] = earned_points
        else:
            questions = Question.objects.filter(question_type__type="Type A")
            questions_with_answers = []
            for question in questions:
                answers = question.answer.all()
                if answers:
                    questions_with_answers.append({'question': question, 'answers': answers})
            context["questions_with_answers"] = questions_with_answers
        return render(request, "dashboard/risk_assessment.html", context)
    

class RiskAssessmentAttemptView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        # Get the list of question-answer pairs from request.POST data
        qa_dict = {}
        selected_answers_ids = request.POST.getlist('answers')
        selected_answers = Answer.objects.filter(id__in=selected_answers_ids)
        for answer in selected_answers:
            question_id = answer.question.id
            if question_id not in qa_dict:
                qa_dict[question_id] = {"question": question_id, "answers": [], "points":[]}
            qa_dict[question_id]["answers"].append(answer.id)
            qa_dict[question_id]["points"].append(answer.points)

        qa = list(qa_dict.values())

        for pair in qa:
            user_attempt = UserAttempt.objects.create(
                user=request.user,
                question=Question.objects.get(id=pair["question"]),
                points_earned=sum(pair["points"]),
                all_question_attempted=True
            )
            user_attempt.selected_answer.set(pair["answers"])
            user_attempt.save()
                    
        return redirect("dashboard:dashboard")



class CommonThreatView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = {"title":"common_threat"}
        return render(request, "dashboard/common_threat.html", context)



# def search_product_vendor(data, product, vendor):
#     results = []
#     for data in data:
#         for container in data.get("containers", {}).values():
#             for affected in container.get("affected", []):
#                 if affected.get("product", "").lower() == product.lower() and affected.get("vendor", "").lower() == vendor.lower():
#                     results.append(container)
#     return results

def search_product_vendor(data, product, vendor):
    results = []
    for data_item in data:
        for container in data_item.get("containers", {}).values():
            for affected in container.get("affected", []):
                if affected.get("product", "").lower() == product.lower() and \
                        affected.get("vendor", "").lower() == vendor.lower():
                    result = {
                        "cveId": data_item.get("cveMetadata", {}).get("cveId"),
                        "versions": affected.get("versions"),
                        "descriptions": container.get("problemTypes"),
                    }
                    results.append(result)
    return results


class AssetsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        qs = Assets.objects.filter(is_deleted=False, user=request.user).values()
        for asset in qs:
            # results = search_product_vendor(OPENCVEDB_DATA, "Apache Tomcat", "Apache Software Foundation")
            results = search_product_vendor(OPENCVEDB_DATA, asset.get("os"), asset.get("software"))
            formatted_results = []
            for result in results:
                formatted_result = json.dumps(result, indent=4)  # Indent for better readability
                formatted_results.append(formatted_result)
            asset["open_cve_data"] = formatted_results

            # asset.update({"open_cve_data":res})

        context = {"datas":qs, "title":"assets"}
        return render(request, "dashboard/assets.html", context)
    
class TrainingsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = {"title":"trainings"}
        return render(request, "dashboard/trainings.html", context)
    
class ComplianceView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = {"title":"compilance"}
        questions = Question.objects.filter(question_type__type="Type B")
        questions_with_answers = []
        for question in questions:
            answers = question.answer.all()
            if answers:
                questions_with_answers.append({'question': question, 'answers': answers})
        context["questions_with_answers"] = questions_with_answers
        return render(request, "dashboard/compilance.html", context)
    
class AboutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        qs = About.objects.filter(is_deleted=False)
        context = {"about":qs, "title":"about"}
        return render(request, "dashboard/about.html", context)
    

class CompilanceQAAttemptView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        # Get the list of question-answer pairs from request.POST data
        qa_dict = {}
        selected_answers_ids = request.POST.getlist('answers')
        selected_answers = Answer.objects.filter(id__in=selected_answers_ids)
        total_points = 0
        for answer in selected_answers:
            question_id = answer.question.id
            if question_id not in qa_dict:
                qa_dict[question_id] = {"question": question_id, "answers": [], "points":[]}
            qa_dict[question_id]["answers"].append(answer.id)
            qa_dict[question_id]["points"].append(answer.points)
            total_points += answer.points

        qa = list(qa_dict.values())
        # print("l115", qa)

        messages.success(request, f"Your attempt was successful. Total points: {total_points}")

        return redirect("dashboard:compilance")
    

class AssetsUploadView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        if 'file' not in request.FILES:
            messages.error(request, "Please select a file to upload")
            return redirect("dashboard:assets")

        file = request.FILES['file']

        file_name = file.name
        file_extension = file_name.split(".")[-1]
        if 'csv' not in file_extension:
            messages.error(request, "Please upload in CSV format.")
            return redirect("dashboard:assets")
        
        try:
            data = validate_and_import_csv(file, user=request.user)
            messages.success(request, "Data imported successfully")
        except Exception as e:
            messages.error(request, str(e))

        return redirect("dashboard:assets")
    
class ExportAssetsDataView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        response = export_assets_data(request)
        return response
    


class RiskRegisterView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        risk_register = RiskRegister.objects.filter(user=request.user, is_deleted=False).values()
        
        for item in risk_register:
            # Calculate PRIORITY LEVEL
            item['priority_level'] = item['impact_level'] * item['probability_level']
            
            # Fetch color code from RiskScore model
            risk_score = RiskScale.objects.filter(number=item['priority_level']).first()
            if risk_score:
                item['color_code'] = risk_score.color_code
            else:
                item['color_code'] = "#FFFFFF"
        
        context={"title":"risk_register", "risk_registers": risk_register}
        return render(request, "dashboard/risk-register.html", context)
    

class RiskRegisterCreateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        data = request.POST
        risk_desc = data.get("riskDesc")
        impactDesc = data.get("impactDesc")
        impactLevel = data.get("impactLevel")
        probalityLevel = data.get("probalityLevel")
        migrationsNotes = data.get("migrationsNotes")
        owner = data.get("owner")

        level = ['1','2','3','4','5']

        valid_impact_level = any(lvl in level for lvl in impactLevel)
        valid_probality_level = any(lvl in level for lvl in probalityLevel)
        
        if not (valid_impact_level and valid_probality_level):
            messages.error(request, "Please select a valid impact level and probability level")
            return redirect("dashboard:risk_register")

        risk_register = RiskRegister(
            user=request.user,
            risk_description=risk_desc,
            impact_description=impactDesc,
            impact_level=impactLevel,

dashboard/templates/dashboard/about.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block content %}

<main class="content px-4 py-5">
    <div class="container-fluid">
        <div class="mb-3">
            <h4>About Us</h4>
        </div>
        <div class="row">
            <div class="col-12 bg-white p-5">
                {% for about in about %}
                        <div class="card-body">
                            <h5 class="card-title text-center mb-3">{{ about.title }}</h5>
                            <p class="mt-3 mb-5">{{ about.description }}</p>
                        </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>

<script>

</script>

{% endblock content %}

dashboard/templates/dashboard/common_threat.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block content %}

<main class="content px-4 py-5">
    <div class="container-fluid">
        <div class="mb-3">
            <h4>Common Threat</h4>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Common Threat Content</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<script>

</script>

{% endblock content %}

dashboard/templates/dashboard/compilance.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block content %}

<main class="content px-4 py-5">
    <div class="container-fluid">
        <div class="mb-3">
            <h4>Compilance</h4>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card mb-3">
                    <div class="card-body">
                        {% if questions_with_answers %}
                            <form method="post" id="assessment-form" action="{% url 'dashboard:compilance_qa_attempt' %}">
                                {% csrf_token %}
                                {% for item in questions_with_answers %}
                                    <div class="card mb-3">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ item.question.title }}</h5>
                                            {% for ans in item.answers %}
                                                <div class="form-check">
                                                    <input class="form-check-input" type="checkbox" name="answers" id="answer{{ ans.id }}" value="{{ ans.id }}" data-question="{{ item.question.id }}">
                                                    <label class="form-check-label" for="answer{{ ans.id }}">
                                                        {{ ans.ans }}
                                                    </label>
                                                </div>
                                            {% endfor %}
                                            <div class="invalid-feedback" style="display: none;">Please select at least one answer.</div>
                                        </div>
                                    </div>
                                {% endfor %}
                                <button type="submit" class="btn btn-primary mt-3">Submit</button>
                                <button type="reset" class="btn btn-secondary mt-3 ml-2">Reset</button>
                            </form>
                        {% else %}
                        <h5>There is no any MCQs please visit later....</h5>
                        {% endif %}
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>


<script>
    document.getElementById("assessment-form").addEventListener("submit", function(event) {
        var questions = document.querySelectorAll('[data-question]');
        var isValid = true;
        questions.forEach(function(question) {
            var checkboxes = document.querySelectorAll('[data-question="' + question.dataset.question + '"]:checked');
            if (checkboxes.length === 0) {
                isValid = false;
                // Show the error message for this question
                question.closest('.card').querySelector('.invalid-feedback').style.display = "block";
            }
        });
        if (!isValid) {
            // Show alert message
            // alert("Please select at least one answer for each question.");
            event.preventDefault();
        }
    });
</script>

{% endblock content %}

dashboard/templates/dashboard/dash.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block content %}

<main class="content px-4 py-5">
    <div class="container-fluid">
        <div class="mb-3">
            <h4>Dashboard</h4>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card mb-3">
                    <div class="card-body">
                        <img src="{% static 'images/dash.png' %}" class="img-fluid" alt="...">
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>


{% endblock content %}

dashboard/templates/dashboard/risk_assessment.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block content %}

<main class="content px-4 py-5">
    <div class="container-fluid">
        <div class="mb-3">
            <h4>Risk Assessment</h4>
        </div>
        <div class="row">
            <div class="col-12">
                {% if earned_points %}

                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">You Have Already Attempted Quizes</h5>
                            
                            <h6>You have earned points: {{ earned_points }}</h6><br>
                            <h6><strong>Risk Level Interpretation:</strong><h6><br>
                                <p><strong>High Risk (Score above 30):</strong><br>
                                    Your organization has significant cybersecurity weaknesses across multiple control categories. Urgent action is needed to implement security measures and improve your overall security posture. Consider seeking professional assistance for a comprehensive risk assessment and remediation plan.</p>
        
                                <p><strong>Medium Risk (Score between 20 and 30):</strong><br>
                                    Your organization has some security gaps that require attention. Prioritize improvements in areas with the highest scores within the questionnaire. Regularly review and update your security controls.</p>
        
                                <p><strong>Low Risk (Score below 20):</strong><br>
                                    Your organization has implemented many good security practices. However, it's crucial to maintain vigilance and continuously monitor for new threats. Regularly test your security controls and conduct security awareness training for employees.</p>
                        </div>
                    </div>

                {% else %}
                    {% if questions_with_answers %}
                    <form method="post" id="assessment-form" action="{% url 'dashboard:risk_assessment_attempt' %}">
                        {% csrf_token %}
                        {% for item in questions_with_answers %}
                            <div class="card mb-3">
                                <div class="card-body">
                                    <h5 class="card-title">{{ item.question.title }}</h5>
                                    {% for ans in item.answers %}
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="answers" id="answer{{ ans.id }}" value="{{ ans.id }}" data-question="{{ item.question.id }}">
                                            <label class="form-check-label" for="answer{{ ans.id }}">
                                                {{ ans.ans }}
                                            </label>
                                        </div>
                                    {% endfor %}
                                    <div class="invalid-feedback" style="display: none;">Please select at least one answer.</div>
                                </div>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary mt-3">Submit</button>
                        <button type="reset" class="btn btn-secondary mt-3 ml-2">Reset</button>
                    </form>
                    {% else %}
                    <h5>There is no any MCQs please visit later....</h5>
                    {% endif %}
                    
                {% endif %}
            </div>
        </div>
    </div>
</main>

<script>
document.getElementById("assessment-form").addEventListener("submit", function(event) {
    var questions = document.querySelectorAll('[data-question]');
    var isValid = true;
    questions.forEach(function(question) {
        var checkboxes = document.querySelectorAll('[data-question="' + question.dataset.question + '"]:checked');
        if (checkboxes.length === 0) {
            isValid = false;
            // Show the error message for this question
            question.closest('.card').querySelector('.invalid-feedback').style.display = "block";
        }
    });
    if (!isValid) {
        // Show alert message
        // alert("Please select at least one answer for each question.");
        event.preventDefault();
    }
});
</script>

{% endblock content %}