qa/urls.py
from django.urls import path

app_name="qa"

urlpatterns = [
    # path("dashboard", DashboardView.as_view(), name="dashboard")
]

risk_mgmt_compilance_mapping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user.urls", namespace="user")),
    path('', include("dashboard.urls", namespace="dashboard")),
    path('', include("qa.urls", namespace="qa")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_title = "RMT site admin (DEV)"
admin.site.site_header = "RMT administration"
admin.site.index_title = "RMT administration"

user/urls.py
from django.urls import path
from user.views import (
    LoginView,
    RegisterView,
    LogoutView,
)

app_name="user"

urlpatterns = [
    path("", LoginView.as_view(), name="user_login"),
    path("register/", RegisterView.as_view(), name="user_register"),
    path("logout/", LogoutView.as_view(), name="user_logout"),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Risk Management Tool</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/ae360af17e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block static %}{% endblock static %}
  </head>
  <body>
    <div class="mb-4 logo">
      {% comment %} <img src="" alt="Logo" height=""> {% endcomment %}
      <h3><a href="{% url "user:user_login" %}"> Risk Management Tool</a> </h3>
    </div>
    {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block script %}{% endblock script %}
  </body>
</html>