dashboard/urls.py
from django.urls import path
from dashboard.views import (
    DashView,
    DashboardView,
    RiskAssessmentAttemptView,
    CommonThreatView,
    AssetsView,
    AssetsUploadView,
    ExportAssetsDataView,
    TrainingsView,
    ComplianceView,
    CompilanceQAAttemptView,
    AboutView,
    RiskRegisterView,
    RiskRegisterCreateView,
    RiskRegisterUpdateView,
    RiskRegisterDeleteView,
)

app_name="dashboard"

urlpatterns = [
    path("dashboard", DashView.as_view(), name="dash"),
    path("risk-assessment", DashboardView.as_view(), name="dashboard"),
    path("rist-assessment-attempt", RiskAssessmentAttemptView.as_view(), name="risk_assessment_attempt"),
    path("common-threat", CommonThreatView.as_view(), name="common_threat"),
    path("assets", AssetsView.as_view(), name="assets"),
    path("assets-upload", AssetsUploadView.as_view(), name="assets_upload"),
    path("assets-export", ExportAssetsDataView.as_view(), name="assets_export"),
    path("trainings", TrainingsView.as_view(), name="trainings"),
    path("compilance", ComplianceView.as_view(), name="compilance"),
    path("compilance-qa-attempt", CompilanceQAAttemptView.as_view(), name="compilance_qa_attempt"),
    path("about-us", AboutView.as_view(), name="about"),
    path("risk-register", RiskRegisterView.as_view(), name="risk_register"),
    path("risk-register-create", RiskRegisterCreateView.as_view(), name="risk_register_create"),
    path("risk-register/<int:pk>/update", RiskRegisterUpdateView.as_view(), name="risk_register_update"),
    path("risk-register/<int:pk>/delete", RiskRegisterDeleteView.as_view(), name="risk_register_delete"),
]

qa/urls.py
from django.urls import path

app_name="qa"

urlpatterns = [
    # path("dashboard", DashboardView.as_view(), name="dashboard")
]

risk_mgmt_compilance_mapping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user.urls", namespace="user")),
    path('', include("dashboard.urls", namespace="dashboard")),
    path('', include("qa.urls", namespace="qa")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_title = "RMT site admin (DEV)"
admin.site.site_header = "RMT administration"
admin.site.index_title = "RMT administration"

user/urls.py
from django.urls import path
from user.views import (
    LoginView,
    RegisterView,
    LogoutView,
)

app_name="user"

urlpatterns = [
    path("", LoginView.as_view(), name="user_login"),
    path("register/", RegisterView.as_view(), name="user_register"),
    path("logout/", LogoutView.as_view(), name="user_logout"),
]

dashboard/models.py
from django.db import models
from utils.models import AbstractTimeStampModel
from user.models import User

class About(AbstractTimeStampModel):
    title = models.CharField(max_length=255)
    description = models.TextField()

    class Meta:
        verbose_name = "About"
        verbose_name_plural = "About"
        db_table = "about"

    def __str__(self):
        return self.title
    

class Assets(AbstractTimeStampModel):
    user = models.ForeignKey(User, verbose_name="User", on_delete=models.CASCADE)
    host_name = models.CharField(max_length=255, verbose_name="Host Name")
    ip_address = models.CharField(max_length=255, verbose_name="IP Address", null=True, blank=True)
    os = models.CharField(max_length=255, verbose_name="OS", null=True, blank=True)
    software = models.CharField(max_length=255, verbose_name="Software", null=True, blank=True)
    other = models.JSONField(default=dict, verbose_name="Other")
    
    class Meta:
        verbose_name = "Assets"
        verbose_name_plural = "Assets"
        db_table = "assets"

    def __str__(self):
        return self.host_name
    


class RiskScale(AbstractTimeStampModel):
    number = models.IntegerField(default=0, verbose_name="Number")
    color_code = models.CharField(max_length=20, verbose_name="Hex Color Code")
    other = models.JSONField(default=dict, verbose_name="Other", null=True, blank=True)

    class Meta:
        verbose_name = "RiskScale"
        verbose_name_plural = "RiskScale"
        db_table = "risk_scale"

    def __str__(self):
        return f"Number: {self.number} Color Code {self.color_code}"
    

class RiskRegister(AbstractTimeStampModel):
    LEVEL_CHOICES = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]
    user = models.ForeignKey(User, verbose_name="User", on_delete=models.CASCADE)
    risk_description = models.TextField(verbose_name="Risk Description", help_text="Give a brief summary of the risk.")
    impact_description = models.TextField(verbose_name="Impact Description", help_text="What will happen if the risk is not mitigated or eliminated?.")
    impact_level = models.IntegerField(choices=LEVEL_CHOICES, verbose_name="Impact Level", help_text="Rate 1 (LOW) to 5 (HIGH).")
    probability_level = models.IntegerField(choices=LEVEL_CHOICES, verbose_name="Probability Level", help_text="Rate 1 (LOW) to 5 (HIGH).")
    migrations_notes = models.TextField(verbose_name="Migration Notes", help_text="What can be done to lower or eliminate the impact or probability?")
    owner = models.TextField(verbose_name="Owner", help_text="Who's responsible?")
    other = models.JSONField(default=dict, verbose_name="Other", null=True, blank=True)

    class Meta:
        verbose_name = "RiskRegister"
        verbose_name_plural = "RiskRegister"
        db_table = "risk_register"

    def __str__(self):
        return self.risk_description

dashboard/forms.py
from django import forms
from qa.models import UserAttempt
from .models import RiskRegister

class RiskAssessmentForm(forms.ModelForm):
    class Meta:
        model = UserAttempt
        fields = ["question", "selected_answer"]


class RiskRegisterForm(forms.ModelForm):
    class Meta:
        model = RiskRegister
        fields = ["risk_description", "impact_description", "impact_level", "probability_level", "migrations_notes", "owner"]
        widgets = {
            'risk_description': forms.Textarea(attrs={'rows': 1}),
            'impact_description': forms.Textarea(attrs={'rows': 1}),
            'migrations_notes': forms.Textarea(attrs={'rows': 1}),
            'owner': forms.Textarea(attrs={'rows': 1})
        }
    
    def __init__(self, *args, **kwargs):
        super(RiskRegisterForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['risk_description'].initial = self.instance.risk_description
            self.fields['impact_description'].initial = self.instance.impact_description
            self.fields['migrations_notes'].initial = self.instance.migrations_notes
            self.fields['owner'].initial = self.instance.owner

dashboard/views.py
import json

from decimal import Decimal
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import View
from qa.models import (
    Question,
    Answer,
    UserAttempt
)
from .models import About, Assets, RiskScale, RiskRegister
from .utils import validate_and_import_csv, export_assets_data
from .OpenCVE.datas import OPENCVEDB_DATA

class DashView(View):
    def get(self, request, *args, **kwargs):
        context = {"title":"dash"}
        return render(request, "dashboard/dash.html", context)

class DashboardView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_attempt = UserAttempt.objects.filter(
            user = request.user,
            all_question_attempted = True,
            question__question_type__type="Type A"
        )
        context = {"title":"dashboard"}
        if user_attempt.exists():
            earned_points = Decimal('0.0')
            for attempted in user_attempt:
                earned_points += attempted.points_earned if attempted.points_earned else Decimal('0.0')
            context["earned_points"] = earned_points
        else:
            questions = Question.objects.filter(question_type__type="Type A")
            questions_with_answers = []
            for question in questions:
                answers = question.answer.all()
                if answers:
                    questions_with_answers.append({'question': question, 'answers': answers})
            context["questions_with_answers"] = questions_with_answers
        return render(request, "dashboard/risk_assessment.html", context)
    

class RiskAssessmentAttemptView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        # Get the list of question-answer pairs from request.POST data
        qa_dict = {}
        selected_answers_ids = request.POST.getlist('answers')
        selected_answers = Answer.objects.filter(id__in=selected_answers_ids)
        for answer in selected_answers:
            question_id = answer.question.id
            if question_id not in qa_dict:
                qa_dict[question_id] = {"question": question_id, "answers": [], "points":[]}
            qa_dict[question_id]["answers"].append(answer.id)
            qa_dict[question_id]["points"].append(answer.points)

        qa = list(qa_dict.values())

        for pair in qa:
            user_attempt = UserAttempt.objects.create(
                user=request.user,
                question=Question.objects.get(id=pair["question"]),
                points_earned=sum(pair["points"]),
                all_question_attempted=True
            )
            user_attempt.selected_answer.set(pair["answers"])
            user_attempt.save()
                    
        return redirect("dashboard:dashboard")



class CommonThreatView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = {"title":"common_threat"}
        return render(request, "dashboard/common_threat.html", context)



# def search_product_vendor(data, product, vendor):
#     results = []
#     for data in data:
#         for container in data.get("containers", {}).values():
#             for affected in container.get("affected", []):
#                 if affected.get("product", "").lower() == product.lower() and affected.get("vendor", "").lower() == vendor.lower():
#                     results.append(container)
#     return results

def search_product_vendor(data, product, vendor):
    results = []
    for data_item in data:
        for container in data_item.get("containers", {}).values():
            for affected in container.get("affected", []):
                if affected.get("product", "").lower() == product.lower() and \
                        affected.get("vendor", "").lower() == vendor.lower():
                    result = {
                        "cveId": data_item.get("cveMetadata", {}).get("cveId"),
                        "versions": affected.get("versions"),
                        "descriptions": container.get("problemTypes"),
                    }
                    results.append(result)
    return results


class AssetsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        qs = Assets.objects.filter(is_deleted=False, user=request.user).values()
        for asset in qs:
            # results = search_product_vendor(OPENCVEDB_DATA, "Apache Tomcat", "Apache Software Foundation")
            results = search_product_vendor(OPENCVEDB_DATA, asset.get("os"), asset.get("software"))
            formatted_results = []
            for result in results:
                formatted_result = json.dumps(result, indent=4)  # Indent for better readability
                formatted_results.append(formatted_result)
            asset["open_cve_data"] = formatted_results

            # asset.update({"open_cve_data":res})

        context = {"datas":qs, "title":"assets"}
        return render(request, "dashboard/assets.html", context)
    
class TrainingsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = {"title":"trainings"}
        return render(request, "dashboard/trainings.html", context)
    
class ComplianceView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = {"title":"compilance"}
        questions = Question.objects.filter(question_type__type="Type B")
        questions_with_answers = []
        for question in questions:
            answers = question.answer.all()
            if answers:
                questions_with_answers.append({'question': question, 'answers': answers})
        context["questions_with_answers"] = questions_with_answers
        return render(request, "dashboard/compilance.html", context)
    
class AboutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        qs = About.objects.filter(is_deleted=False)
        context = {"about":qs, "title":"about"}
        return render(request, "dashboard/about.html", context)
    

class CompilanceQAAttemptView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        # Get the list of question-answer pairs from request.POST data
        qa_dict = {}
        selected_answers_ids = request.POST.getlist('answers')
        selected_answers = Answer.objects.filter(id__in=selected_answers_ids)
        total_points = 0
        for answer in selected_answers:
            question_id = answer.question.id
            if question_id not in qa_dict:
                qa_dict[question_id] = {"question": question_id, "answers": [], "points":[]}
            qa_dict[question_id]["answers"].append(answer.id)
            qa_dict[question_id]["points"].append(answer.points)
            total_points += answer.points

        qa = list(qa_dict.values())
        # print("l115", qa)

        messages.success(request, f"Your attempt was successful. Total points: {total_points}")

        return redirect("dashboard:compilance")
    

class AssetsUploadView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        if 'file' not in request.FILES:
            messages.error(request, "Please select a file to upload")
            return redirect("dashboard:assets")

        file = request.FILES['file']

        file_name = file.name
        file_extension = file_name.split(".")[-1]
        if 'csv' not in file_extension:
            messages.error(request, "Please upload in CSV format.")
            return redirect("dashboard:assets")
        
        try:
            data = validate_and_import_csv(file, user=request.user)
            messages.success(request, "Data imported successfully")
        except Exception as e:
            messages.error(request, str(e))

        return redirect("dashboard:assets")
    
class ExportAssetsDataView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        response = export_assets_data(request)
        return response
    


class RiskRegisterView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        risk_register = RiskRegister.objects.filter(user=request.user, is_deleted=False).values()
        
        for item in risk_register:
            # Calculate PRIORITY LEVEL
            item['priority_level'] = item['impact_level'] * item['probability_level']
            
            # Fetch color code from RiskScore model
            risk_score = RiskScale.objects.filter(number=item['priority_level']).first()
            if risk_score:
                item['color_code'] = risk_score.color_code
            else:
                item['color_code'] = "#FFFFFF"
        
        context={"title":"risk_register", "risk_registers": risk_register}
        return render(request, "dashboard/risk-register.html", context)
    

class RiskRegisterCreateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        data = request.POST
        risk_desc = data.get("riskDesc")
        impactDesc = data.get("impactDesc")
        impactLevel = data.get("impactLevel")
        probalityLevel = data.get("probalityLevel")
        migrationsNotes = data.get("migrationsNotes")
        owner = data.get("owner")

        level = ['1','2','3','4','5']

        valid_impact_level = any(lvl in level for lvl in impactLevel)
        valid_probality_level = any(lvl in level for lvl in probalityLevel)
        
        if not (valid_impact_level and valid_probality_level):
            messages.error(request, "Please select a valid impact level and probability level")
            return redirect("dashboard:risk_register")

        risk_register = RiskRegister(
            user=request.user,
            risk_description=risk_desc,
            impact_description=impactDesc,
            impact_level=impactLevel,

templates/dashboard/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Risk Management Tool</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/ae360af17e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/dashboard/main.css' %}">
</head>

<body>
    <div class="wrapper">
        <aside id="sidebar" class="js-sidebar">
            <!-- Content For Sidebar -->
            <div class="h-100">
                <div class="sidebar-logo">
                    <a href="#"> <img src="{% static 'images/icon.jpg' %}" alt="" style="height: 50px; width: 50px;"> <span style="color: black;">RMT</span></a>
                </div>
                <ul class="sidebar-nav">
                    <li class="sidebar-header">
                        
                    </li>
                    <li class="sidebar-item side-item">
                        <a href="{% url "dashboard:dash" %}" class="sidebar-link {% if title == 'dash' %}active{% endif %}">
                            <i class="fa-solid fa-square-minus pe-2"></i>
                            Dashboard
                        </a>
                    </li>
                    <li class="sidebar-item side-item">
                        <a href="{% url "dashboard:dashboard" %}" class="sidebar-link {% if title == 'dashboard' %}active{% endif %}">
                            <i class="fa-solid fa-list pe-2"></i>
                            Risk Assessment
                        </a>
                    </li>
                    {% comment %} <li class="sidebar-item side-item">
                        <a href=" {% url "dashboard:common_threat" %} " class="sidebar-link {% if title == 'common_threat' %}active{% endif %}">
                            <i class="fa-solid fa-triangle-exclamation pe-2"></i>
                            Common Threat
                        </a>
                    </li> {% endcomment %}
                    <li class="sidebar-item side-item">
                        <a href="{% url 'dashboard:risk_register' %}" class="sidebar-link {% if title == 'risk_register' %}active{% endif %}">
                            <i class="fa-solid fa-cash-register"></i>
                            Risk Register
                        </a>
                    </li>
                    <li class="sidebar-item side-item">
                        <a href="{% url "dashboard:compilance" %}" class="sidebar-link {% if title == 'compilance' %}active{% endif %}">
                            <i class="fa-solid fa-toolbox pe-2"></i>
                            Compliance
                        </a>
                    </li>
                    <li class="sidebar-item side-item">
                        <a href="{% url "dashboard:about" %}" class="sidebar-link {% if title == 'about' %}active{% endif %}">
                            <i class="fa-solid fa-circle-info pe-2"></i>
                            About
                        </a>
                    </li>
                    <li class="sidebar-item side-item">
                        <a href="" class="sidebar-link">
                            <form action="{% url 'user:user_logout' %}" method="POST">
                                {% csrf_token %}
                                <div class="sidebar-link">
                                    <button type="submit" class="btn_logout"><i class="fa-solid fa-right-from-bracket pe-2"></i> Logout</button>
                                </div>
                            </form>
                        </a>
                        
                    </li>
                </ul>
            </div>
        </aside>
        <div class="main">
            <nav class="navbar navbar-expand px-4 border-bottom bg-white">
                <button class="btn" id="sidebar-toggle" type="button">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse navbar">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <img src="{% static 'images/body_bg.jpg' %}" class="avatar img-fluid rounded-circle" alt="">
                        </li>
                    </ul>
                </div>
            </nav>
            
            {% if messages %}
                <div class="p-4">
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                {% for message in messages %}
                                <div class="alert alert-danger">
                                    {{ message }}
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
            
            
            {% block content %}
            
            {% endblock content %}

            <footer class="footer">
                <div class="container-fluid">
                    
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        const sidebarToggle = document.querySelector("#sidebar-toggle");
        sidebarToggle.addEventListener("click",function(){
            document.querySelector("#sidebar").classList.toggle("collapsed");
        });



        const sidebarList = document.querySelectorAll(".side-item a")

        sidebarList.forEach((list) => {
            list.addEventListener("click", () => {
                sidebarList.forEach((list) => {
                    list.classList.remove("active")
                })
            list.classList.add("active")

            })
        })
    </script>
</body>

</html>